test for existence of filesystem before checking type
Summary: Right now, this method can return a `NoMethodError: undefined method `[]' for nil:NilClass` on windows hosts because we are not checking for the existence of the data before iterating on it.

Reviewed By: petermblair

Differential Revision: D20959594

fbshipit-source-id: 5a46f5369042fcd8ff026404f669c1e314e09c5e